### ISSUE TITLE
awsall does not work after following install instructions

### ISSUE THREAD

**Issue by thomasdpage** [antonbabenko/awsp#3]
Hi,

`awsall` does not work after following the install instructions.

```
awsall
bash: _awsConfigListAll: command not found
```

Thanks

**Comment by pbsladek** [comment]
@thomasdpage Can just change your alias:

`alias awsa="_awsListAll"`

Was changed here in the readme: https://github.com/antonbabenko/awsp/commit/65881913c1dc3aa1f8e0daf4e9daf9d3dc363276
